### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by jjclark1982** [dungeon-diagrams/dungeon-diagrams.github.io#1]
#### Puzzle Model

- [x] define glyphs for each tile type
- [x] use class hierarchy to express type matching rules (eg, is a tile a Floor or any subclass of Floor)
- [x] set tile cycle order based on editability
- [x] verify wall counts
- [x] verify dead ends
- [x] verify treasure rooms
- [x] verify 2x2 halls
- [x] verify connectivity (use a union-find data structure separate from `puzzle.tiles`, reset it when adding walls but not when removing them)

#### Serialization (puzzle-strings and router)

- [x] convert a puzzle to/from an emoji string that displays in a grid
- [x] convert a puzzle to/from an ascii string
- [x] support strings with compact URL encodings (`.-_~!*'()`)
- [x] convert to a URL with spec in search and state in hash
- [ ] convert from a URL with spec in search and state in hash
- [x] make a list of links to serialized puzzles
- [x] debug linking error for The Twin Cities of the Dead

#### Daily Seeds

- [x] generate a puzzle from a given seed
- [x] generate a seed based on the current date

#### Persistence (puzzle-ids and preferences)

- [x] support manually setting dark mode and high-contrast mode
- [ ] record daily results and winning streak
- [ ] store an edited or incomplete puzzle in local storage

#### Style

- [x] make cells always square regardless of content
- [x] scale table to viewport size regardless of dimensions
- [x] scale content to cells regardless of viewport size
- [x] detect emoji availability and fall back ~~or bundle a font~~
- [x] animate target numbers when correct
- [x] animate monsters when solved
- [x] mobile layout for settings menu
- [ ] mobile layout for editing tools
- [x] respect stored preferences for color scheme
- [ ] don't show "Loading..." unless it takes more than 100ms
- [ ] highlight disconnected hallways
- [x] modal layer for menu

#### Puzzle Solving Interface

- [x] support right-click to mark empty on desktop
- [x] set tile cycle order based on platform (disable left-click to mark empty when right-click is available) - maybe check `window.navigator.maxTouchPoints`, maybe store a configuration
- [x] unmark floors when a puzzle gets solved
- [ ] support "undo" of a multi-tile change - something like `history.pushState()` after every `swipeEnd` action, but without breaking the back button
- [ ] record time taken to solve
- [x] disable input once a puzzle is solved
- [ ] include instructions/tutorial

#### Puzzle Editing Interface

- [x] UI to toggle editing mode
- [x] field to set puzzle name
- [x] fields to set grid dimensions
- [x] UI to manually enter wall counts
- [x] function to automatically update wall counts
- [x] tool to cycle through all tile types 
- [x] "magic wall" tool to automatically place monsters in dead ends
- [x] UI to set glyph for auto-monster
- [x] tool to place a monster (support custom glyph)
- [x] tool to place a treasure (support custom glyph)
- [ ] create link to unsolved puzzle when a solution exists
- [ ] display tile connectivity
- [x] make brush stroke continue through puzzle 'change' events
- [x] make brush stroke reset when changing tools
- [ ] UI to pick emojis

#### Deployment (web / mobile)

- [x] build with GitHub Actions
- [x] deploy to GitHub Pages
- [x] test that the app is capable of initializing, before deployment
- [x] run browser-only tests in CI (phantom.js and zombie.js don't appear to meet the app requirements, jsdom does)
- [x] use es-module-shims to support older browsers and importmaps
- [x] custom domain name or organization name
- [ ] favicon
- [x] `meta` tags for search/social links
- [x] manifest for "add to home screen"
- [x] consider using jest for tests
- [ ] use eslint
- [x] set current date based on server clock, fall back to some fixed time zone
- [ ] use different titles for embedded links to different pages

#### Deployment (terminal / BBS)

- [x] remove window/document/font dependencies from puzzle model
- [x] set current date based on system clock

#### Accessibility

- [ ] keyboard interface for puzzle interactons
- [ ] aria markup
